modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="medievalmc"
version="1.0.0"
displayName="MedievalMC"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Jan, MCreator"

[[dependencies.medievalmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




