modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="medievalmc"
version="1.0.0-alpha-2"
displayName="MedievalMC"
credits="Made using MCreator - Check it out!"
displayURL="https://eclypse.dev/"
authors="4FA"
description='''
MedievalMC is a modification for Minecraft aiming to add tons of medieval weapons and items. 
'''

[[dependencies.medievalmc]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




